# Generated by Django 4.2 on 2025-12-03 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('estoque', '0003_item_categoria_solicitacao_indexes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['descricao']},
        ),
        migrations.AlterModelOptions(
            name='movimentacao',
            options={'ordering': ['-data']},
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='estoque_ite_codigo_37b449_idx',
            old_name='estoque_ite_codigo_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='estoque_ite_descric_47668d_idx',
            old_name='estoque_ite_descric_idx',
        ),
        migrations.RenameIndex(
            model_name='item',
            new_name='estoque_ite_categor_0d0a6b_idx',
            old_name='estoque_ite_categor_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacao',
            new_name='estoque_mov_item_id_72fd74_idx',
            old_name='estoque_mov_item_data_idx',
        ),
        migrations.RenameIndex(
            model_name='movimentacao',
            new_name='estoque_mov_tipo_b96410_idx',
            old_name='estoque_mov_tipo_data_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitacao',
            new_name='estoque_sol_item_id_0da139_idx',
            old_name='estoque_sol_item_status_idx',
        ),
        migrations.RenameIndex(
            model_name='solicitacao',
            new_name='estoque_sol_solicit_1d89af_idx',
            old_name='estoque_sol_solicit_status_idx',
        ),
    ]
